### ISSUE TITLE
Blog Error 

### ISSUE THREAD

**Issue by Sharelter** [Angelic47/Angelic47#1]
Chromium的报告
www.angelic47.com 通常会使用加密技术来保护您的信息。Chromium 此次尝试连接到 www.angelic47.com 时，此网站发回了异常的错误凭据。这可能是因为有攻击者在试图冒充 www.angelic47.com，或 Wi-Fi 登录屏幕中断了此次连接。请放心，您的信息仍然是安全的，因为 Chromium 尚未进行任何数据交换便停止了连接。

-------------------------------------------
下面是Firefox的报告

www.angelic47.com 使用了无效的安全证书。 该证书因为其自签名而不被信任。 该证书对名称 www.angelic47.com 无效。 错误代码: SEC_ERROR_UNKNOWN_ISSUER

**Comment by Angelic47** [comment]
你好，刚刚我已经测试过了blog并无上述问题。
建议你检查一下你的浏览器软件是否有问题，以及网络运营商是否劫持了连接(更换网络或使用手机蜂窝热点再做测试)
此外我的blog只支持https访问

**Comment by Sharelter** [comment]
emmm...我ping到的是219.146.244.52
DNS是Cloudflare提供的1.1.1.1

**Comment by Angelic47** [comment]
blog使用了cdn，ping到的ip没有实际意义。但是既然浏览器已经提示证书错误了，还请你多自行排查一下自己的网络环境是否存在劫持

**Comment by Angelic47** [comment]
issue已做关闭处理，原因是客户端自身环境问题
